package Practice2;

public class ExceptionConcept {
//    public static void main(String[] args) {
//        System.out.println("Main Starts");
//        
//        System.out.println("Executing the code...");
//        
//        System.out.println("Main Ends");
//        /*
//        Gracefull termination
//        */ 
//        
//    }
//    public static void main(String[] args) {
//        System.out.println("Main Starts");
//        
//        System.out.println("Executing the code...");
//        
//        System.exit(0);
//        
//        System.out.println("Main Ends");
//        /*
//        Terminates the execution
//        Force Termination at line 20
//        */ 
//        
//    }   
    
//    public static void main(String[] args) {
//        System.out.println("Main Starts");
//        
//        System.out.println("Executing the code...");
//        
//        System.out.println(10/0);
//        
//        System.out.println("Main Ends");
//       
//        /*
//          Abrupt Termination, caused by the exception
//          if not handled
//        
//          In this case memory will be flushed out, data loss will take place 
//        
//          Aboce two cases are in the control of a programmer, but not this one
//        */ 
//    }

     
    
    public static void main(String[] args) {
        
    }        
}
